version: '3'
services:
  # Teedy Application
  teedy-server:
    image: sismics/docs:latest
    ports:
      # Map internal port to host
      - 8080:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://localhost"
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      # credentials: admin/admin